// webview-ui/src/App.vue
<template>
  <div class="app">
    <CardList :items="items" @remove-item="removeItem" />
    <div class="search-container">
      <SearchBar @search="handleSearch" :is-loading="isLoading" />
    </div>
    <Toast :message="toastMessage" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { vscode } from './utilities/vscode'
import CardList from './components/CardList.vue'
import SearchBar from './components/SearchBar.vue'
import Toast from './components/Toast.vue'

interface QueryResult {
  id: string
  query: string
  timestamp: number
  status: 'loading' | 'success' | 'error'
  result?: any
  error?: string
}

const items = ref<QueryResult[]>([])
const toastMessage = ref('')
const isLoading = ref(false)

const handleSearch = (inputValue: string) => {
  if (!inputValue.trim()) {
    return
  }
  
  if (inputValue === '/clear') {
    items.value = []
    return
  }

  // 检查是否已存在相同查询
  const existingIndex = items.value.findIndex(item => 
    item.query === inputValue && item.status === 'success'
  )
  
  if (existingIndex !== -1) {
    toastMessage.value = '该查询已存在，请查看历史记录'
    setTimeout(() => {
      toastMessage.value = ''
    }, 2000)
    return
  }

  // 添加加载状态
  const queryId = Date.now().toString()
  const newQuery: QueryResult = {
    id: queryId,
    query: inputValue,
    timestamp: Date.now(),
    status: 'loading'
  }
  
  items.value = [...items.value, newQuery]
  isLoading.value = true
  
  vscode.postMessage({ command: 'parseUUID', text: inputValue })
}

onMounted(() => {
  window.addEventListener('message', (event) => {
    const message = event.data
    if (message.command === 'parseUUID_resp') {
      console.log('search===', message.text)
      isLoading.value = false
      
      const info = message.text
      if (info.code) {
        // 错误查询不显示在列表中，只显示吐司提示
        // 移除加载中的查询项（最新查询在底部）
        if (items.value.length > 0 && items.value[items.value.length - 1].status === 'loading') {
          items.value = items.value.slice(0, -1)
        }
        
        let errorMessage = 'UUID格式无效'
        if (info.code === 'NOT_FOUND') {
          errorMessage = info.message || '未找到对应的资源'
        }
        
        toastMessage.value = errorMessage
        setTimeout(() => {
          toastMessage.value = ''
        }, 2000)
        return
      }
      
      // 检查查询结果是否有效
      if (!info || Object.keys(info).length === 0) {
        // 查询结果为空，不显示在列表中（最新查询在底部）
        if (items.value.length > 0 && items.value[items.value.length - 1].status === 'loading') {
          items.value = items.value.slice(0, -1)
        }
        toastMessage.value = '未找到对应的资源'
        setTimeout(() => {
          toastMessage.value = ''
        }, 2000)
        return
      }
      
      // 只有成功查询才显示在列表中（最新查询在底部）
      if (items.value.length > 0) {
        items.value[items.value.length - 1].status = 'success'
        items.value[items.value.length - 1].result = info
      }
    }
  })
})

const removeItem = (index: number) => {
  items.value = items.value.filter((_, i) => i !== index)
}
</script>

<style scoped>
.app {
  height: 100vh;
  display: flex;
  flex-direction: column;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

.search-container {
  padding: 12px 16px;
  background-color: #1e1e1e;
  border-top: 1px solid #3c3c3c;
  flex-shrink: 0;
  box-sizing: border-box;
  margin: 0;
}
</style>

// webview-ui/src/App.tsx
import React, { KeyboardEventHandler, useState, useEffect, useContext } from 'react';
import { VSCodeButton, VSCodeTextField, VSCodeTextArea } from '@vscode/webview-ui-toolkit/react';
import { vscode } from "./utilities/vscode";
// 帮我导入css样式文件
import './App.css';

type CardProps = {
  children: React.ReactNode;
  onRemove: () => void;
};

const MyDiv = ({ data, onClose }: { data: object, onClose: () => void }) => {
  return (
    <div style={{ position: 'relative' }}>
      <div className="panel">
        {Object.entries(data).map(([key, value]) => (
          <div key={key} className="item">
            <span className="key">{key}</span>: <span className="value">{value}</span>
          </div>
        ))}
      </div>
      <VSCodeButton style={{
        position: 'absolute',
        top: '0px',
        right: '0px',
        borderRadius: '50%',
        width: '20px',
        height: '20px',
        padding: '1px',
        fontSize: '0.5rem',
        backgroundColor: 'gray',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      }}
        onClick={onClose}>x</VSCodeButton>
    </div>
  );
};

const Card = ({ children, onRemove }: CardProps) => {
  return (
    <div style={{
      // border: '1px solid #ccc',
      // borderRadius: '10px',
      padding: '0px',
      margin: '0px',
      position: 'relative'
    }}>
      {children}
      <VSCodeButton style={{
        position: 'absolute',
        top: '0px',
        right: '0px',
        borderRadius: '50%',
        width: '20px',
        height: '20px',
        padding: '1px',
        fontSize: '0.5rem',
        backgroundColor: 'gray',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      }}
        onClick={onRemove}>x</VSCodeButton>
    </div>
  );
};

const Welcome = () => {
  return (
    <div style={{ justifyContent: 'center', alignItems: 'center', height: '100%' }}>
      <h1>creator资源查询功能介绍</h1><br />
      <h2>使用案例:</h2>
      <p>1. 输入长UUID: e24d07b2-28d6-4a7e-aa88-91598af8bd80</p>
      <p>2. 输入短UUID: e24d0eyKNZKfqqIkVmK+L2A</p>
      <p>3. 输入路径Path(查图片动画等): new_guide.png</p>
      <p>4. 输入路径Path(查脚本): NewGuideView.ts</p>
      <p>5. 输入路径Path(查功能): resource/activity/demo</p>
      <p>6. 输入/clear: 清除所有查询结果</p>
      <p>如果根据路径查,要写cocos creator项目的相对路径</p>
    </div>
  );
};

const CardList = (props: { items: object[], removeItem: (index: number) => void }) => {
  const { items, removeItem } = props;
  return (
    <div style={{ height: 'calc(100vh - 60px)', overflowY: 'scroll' }}>
      {items.length === 0 && <Welcome />}
      {items.map((item: object, index: number) => <MyDiv data={item} onClose={() => removeItem(index)} />)}
    </div>
  );
};

const SearchBar = ({ onSearch }: { onSearch: (value: string) => void }) => {
  const [value, setValue] = useState<string>('');

  const handleSearch: KeyboardEventHandler<HTMLInputElement> = (e) => {
    if (e.key === 'Enter') {
      if (e.target) {
        const content = e.target as HTMLInputElement;
        onSearch(content.value);
      }
      setValue('');
    }
  };

  return (
    <VSCodeTextField
      value={value}
      onChange={(e) => {
        console.log('VSCodeTextField===', e.target);
      }}
      placeholder="Enter a UUID or Path or '/clear' to clear all items."
      onKeyDown={handleSearch}
      maxlength={512}
      style={{ width: '100%' }}
    />
  );
};

const Toast = ({ message }: { message: string }) => {
  if (!message) {
    return null;
  }

  return (
    <div style={{ position: 'fixed', bottom: '20px', right: '20px', backgroundColor: 'rgba(0,0,0,0.5)', color: 'white', padding: '10px', borderRadius: '5px' }}>
      {message}
    </div>
  );
};

const App = () => {
  const [items, setItems] = useState<object[]>([]);
  const [toastMessage, setToastMessage] = useState('');

  const handleSearch = (inputValue: string) => {
    if (!inputValue) {
      return;
    }
    if (inputValue === '/clear') {
      setItems([]);
      return;
    }
    vscode.postMessage({ command: 'parseUUID', text: inputValue });
  };

  useEffect(() => {
    window.addEventListener('message', (event) => {
      const message = event.data;
      if (message.command === 'parseUUID_resp') {
        console.log('search===', message.text);
        const info = message.text;
        if (info.code) {
          setToastMessage('uuid invaild');
          setTimeout(() => {
            setToastMessage('');
          }, 1200);
          return;
        }
        setItems((prevItems: object[]) => [...prevItems, info]);
      }
    });
  }, []);

  const removeItem = (index: number) => {
    setItems((prevItems: object[]) => prevItems.filter((_: any, i: number) => i !== index));
  };

  return (
    <div>
      <CardList items={items} removeItem={removeItem} />
      <SearchBar onSearch={handleSearch} />
      <Toast message={toastMessage} />
    </div>
  );
};

export default App;
